### ISSUE TITLE
Among Us is a very political game

### ISSUE THREAD

**Issue by matteodev8** [tat2008/TUANS-BOT-MUSIC#1]
What is your political opinion on the video game "Among Us"? In my political opinion, the "Imposter" in "Among Us" is very "suspect" ("Sus"). That is way too political! I already informed Obama about it, but he said I need to find out his last name to sue the video game "Among Us". He told me its in a scroll, deep hidden in an alien base in the arctic. Will you help me?

**Comment by Jimmy-Blue** [comment]
I'd just like to interject for a moment. What you’re referring to as Linux, is in fact, GNU/Linux, or as I’ve recently taken to calling it, GNU plus Linux. Linux is not an operating system unto itself, but rather another free component of a fully functioning GNU system made useful by the GNU corelibs, shell utilities and vital system components comprising a full OS as defined by POSIX.
Many computer users run a modified version of the GNU system every day, without realizing it. Through a peculiar turn of events, the version of GNU which is widely used today is often called “Linux”, and many of its users are not aware that it is basically the GNU system, developed by the GNU Project. There really is a Linux, and these people are using it, but it is just a part of the system they use.
Linux is the kernel: the program in the system that allocates the machine’s resources to the other programs that you run. The kernel is an essential part of an operating system, but useless by itself; it can only function in the context of a complete operating system. Linux is normally used in combination with the GNU operating system: the whole system is basically GNU with Linux added, or GNU/Linux. All the so-called “Linux” distributions are really distributions of GNU/Linux.

**Comment by matteodev8** [comment]
vào mỗi tối khi tôi chuẩn bị ngủ thì tôi lại mơ thấy mình đang ịn mặt lên ngực của Hatsume Miku và điều đó làm tôi rất khoái chí,cặc tôi cương lên một cách lạ kì như hể Shrek đang địt tôi,nói vậy cũng chưa đủ. Tôi muốn được hơn thế,nên mỗi tối tôi lấy con gấu bông ra và tôi địt nó,hai giờ một lần,mỗi lần như vậy con gấu ấy cứ căng lên,sau ba tháng thì nó từ một con gấu bình thường giờ đây trở thành một cái bọc đựng tinh,nứng lắm nên tôi bắt đầu uống nó,vị nó mặn mà dễ chịu làm sao,nó làm tôi càng nứng hơn,ôi,một hương thơm ngào ngạt khiến tôi không thể không quên được khoảng khắc này. Một thứ tình cảm chỉ có ở người đàn ông.
19. Dezember 2021

**Comment by tat2008** [comment]
What?

**Comment by Toasty9004Dev** [comment]
If u open the issue for nothing, don't do it lmao
